repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --args=--lockfile=false
      - id: terraform_tflint
      # - id: terraform_checkov
      # - id: terraform_tfsec
      - id: infracost_breakdown
        verbose: true
        args:
          - --args=--path=nicconf
          - --args=--usage-file=nicconf/infracost_usage.yml
          - --args=--log-level=warn
          - --hook-config='.totalMonthlyCost|tonumber < 10'
